[meta]
name     = "Editor++"
author   = "XertroV"
category = "Map Editor"
version  = "0.8.99991"
siteid   = 377
blocks   = ["item-placement-toolbox", "item-placement-toolbox-dev"]

[script]
#__DEFINES__
dependencies = ["Camera", "VehicleState"]
# optional_dependencies = ["MLHook"]
# some editor things can take a while, like saving the map
timeout  = 7500

shared_exports = ["GBX/GBX.as"]
